import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/*
 * Reloading is NOT done from here. The Hot Reload plugin watches main.js inside
 * Obsidian and reloads on its own, which keeps this build from shelling out to the
 * Obsidian CLI on every save — those calls intermittently pull the Obsidian window
 * to the front and steal focus while you are typing.
 *
 * Requirements, already in place: the Hot Reload plugin enabled in the vault, and a
 * `.hotreload` file in this repo (its `.git` folder would do too).
 */

/*
 * Deploying to a second vault: point OBSIDIAN_DEPLOY_TO at a plugin folder and
 * every successful build copies the three release artifacts there. See the
 * "Testing in your own vault" section of the README for the exact invocation.
 *
 * This exists because the test vault is reached through a symlink to this repo,
 * and that is a bad idea for a vault inside iCloud or any other sync service: the
 * repo carries ~139 MB of node_modules and a .git directory, and putting those
 * inside a synced folder invites the client to upload all of it. Copying only the
 * three files the vault actually needs keeps it clean.
 *
 * The `.hotreload` marker is written alongside them, because Hot Reload only
 * watches plugin folders carrying it (or a `.git`), and a copied folder has
 * neither.
 */
const deployTo = process.env.OBSIDIAN_DEPLOY_TO;

const deployPlugin = {
	name: 'deploy-to-vault',
	setup(build) {
		build.onEnd(async (result) => {
			if (deployTo === undefined || result.errors.length > 0) return;
			try {
				await mkdir(deployTo, { recursive: true });
				for (const file of ['main.js', 'manifest.json', 'styles.css']) {
					if (existsSync(file)) await copyFile(file, join(deployTo, file));
				}
				await writeFile(join(deployTo, '.hotreload'), '');
				console.log(`[deploy] ${deployTo}`);
			} catch (error) {
				// A vault that is not there must not break the build.
				console.log(`[deploy] skipped: ${error.message}`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
