import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync, lstatSync, readFileSync, realpathSync } from 'node:fs';
import { join, resolve } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/*
 * Reloading is NOT done from here. The Hot Reload plugin watches main.js inside
 * Obsidian and reloads on its own, which keeps this build from shelling out to the
 * Obsidian CLI on every save — those calls intermittently pull the Obsidian window
 * to the front and steal focus while you are typing.
 *
 * Requirements, already in place: the Hot Reload plugin enabled in the vault, and a
 * `.hotreload` file in this repo (its `.git` folder would do too).
 */

/*
 * Which vault a build lands in.
 *
 * Vaults are named in `.env.local` (git-ignored, see `.env.local.example`), as
 * vault *roots* — the plugin subfolder is derived from the manifest id, so the
 * same file works unchanged for every plugin you develop:
 *
 *     VAULT_TEST=/Users/you/dev/my-obsidian-plugins
 *     VAULT_REAL=/Users/you/Library/.../YourVault
 *     VAULT_DEFAULT=TEST
 *
 * Pick one with `--vault=real`; without it, `VAULT_DEFAULT` decides. A path is
 * personal and long, and typing it on every invocation is how a good workflow
 * gets abandoned. `loadEnvFile` is built into Node — no dependency.
 *
 * `pnpm build` never installs anywhere: that is the CI path, and writing into
 * somebody's vault as a side effect of a config file existing would be a trap.
 * Installing happens in `dev` and `install:vault`, which pass `deploy`.
 */
const deploy = process.argv.includes('deploy');
if (existsSync('.env.local')) process.loadEnvFile('.env.local');

const { id: pluginId } = JSON.parse(readFileSync('manifest.json', 'utf8'));
const requested = process.argv.find((a) => a.startsWith('--vault='))?.slice('--vault='.length);
const vaultName = (requested ?? process.env.VAULT_DEFAULT ?? '').trim().toUpperCase();
const vaultRoot = vaultName ? process.env[`VAULT_${vaultName}`]?.trim() : undefined;

function resolveTarget() {
	if (!deploy) return undefined;
	if (!vaultName) {
		console.error(
			'No vault chosen. Pass --vault=<name> or set VAULT_DEFAULT in .env.local ' +
				'(copy .env.local.example to start).'
		);
		process.exit(1);
	}
	if (!vaultRoot) {
		const known = Object.keys(process.env)
			.filter((k) => k.startsWith('VAULT_') && k !== 'VAULT_DEFAULT')
			.map((k) => k.slice('VAULT_'.length).toLowerCase());
		console.error(
			`Unknown vault "${vaultName.toLowerCase()}". ` +
				(known.length ? `Defined in .env.local: ${known.join(', ')}.` : 'None defined in .env.local.')
		);
		process.exit(1);
	}
	if (!existsSync(vaultRoot)) {
		console.error(`Vault "${vaultName.toLowerCase()}" does not exist: ${vaultRoot}`);
		process.exit(1);
	}
	const target = join(vaultRoot, '.obsidian', 'plugins', pluginId);
	/*
	 * A vault reached through a symlink to this repo is already live: copying into
	 * it would write main.js onto itself. Say so once and skip, instead of doing
	 * something surprising.
	 */
	if (existsSync(target) && lstatSync(target).isSymbolicLink()) {
		if (realpathSync(target) === resolve('.')) {
			console.log(`[install] ${vaultName.toLowerCase()}: symlinked to this repo, nothing to copy`);
			return undefined;
		}
	}
	return target;
}

const deployTo = resolveTarget();

/*
 * Three files, copied rather than symlinked: a symlink would put this repo's
 * node_modules and .git inside a vault that iCloud, Dropbox or Syncthing is
 * watching. The `.hotreload` marker goes with them, because the Hot Reload plugin
 * only watches plugin folders carrying it or a `.git`.
 */
const deployPlugin = {
	name: 'install-into-vault',
	setup(build) {
		build.onEnd(async (result) => {
			if (deployTo === undefined || result.errors.length > 0) return;
			try {
				await mkdir(deployTo, { recursive: true });
				for (const file of ['main.js', 'manifest.json', 'styles.css']) {
					if (existsSync(file)) await copyFile(file, join(deployTo, file));
				}
				await writeFile(join(deployTo, '.hotreload'), '');
				console.log(`[install] ${vaultName.toLowerCase()} → ${deployTo}`);
			} catch (error) {
				// A vault that went away must not break the build.
				console.log(`[install] skipped: ${error.message}`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
