import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/*
 * Reloading is NOT done from here. The Hot Reload plugin watches main.js inside
 * Obsidian and reloads on its own, which keeps this build from shelling out to the
 * Obsidian CLI on every save — those calls intermittently pull the Obsidian window
 * to the front and steal focus while you are typing.
 *
 * Requirements, already in place: the Hot Reload plugin enabled in the vault, and a
 * `.hotreload` file in this repo (its `.git` folder would do too).
 */

/*
 * Installing into a vault — `pnpm install:vault`, and `pnpm dev:vault` to iterate.
 *
 * Only ever when explicitly asked for, via the `deploy` argument. A plain
 * `pnpm build` must never write into somebody's vault as a side effect of a
 * configuration file being present.
 *
 * The destination is `OBSIDIAN_DEPLOY_TO`, from `.env.local` (git-ignored, see
 * `.env.local.example`) or from the environment. A vault path is personal and
 * long, and typing it on every invocation is how a good workflow gets abandoned.
 * `loadEnvFile` is built into Node — no dependency.
 *
 * Three files are copied rather than symlinked, because a symlink would put this
 * repo's node_modules and .git inside a vault that iCloud, Dropbox or Syncthing
 * is watching. The `.hotreload` marker goes with them so the Hot Reload plugin
 * picks the folder up — it only watches plugin folders carrying it or a `.git`.
 */
const deploy = process.argv.includes('deploy');
if (deploy && existsSync('.env.local')) process.loadEnvFile('.env.local');
// An empty value counts as absent: `OBSIDIAN_DEPLOY_TO=` in a shell would
// otherwise reach `mkdir('')` and fail with something unreadable.
const configured = process.env.OBSIDIAN_DEPLOY_TO?.trim();
const deployTo = deploy && configured ? configured : undefined;

if (deploy && deployTo === undefined) {
	console.error(
		'Nothing to deploy to: set OBSIDIAN_DEPLOY_TO in .env.local (copy .env.local.example) ' +
			'or pass it in the environment.'
	);
	process.exit(1);
}

const deployPlugin = {
	name: 'deploy-to-vault',
	setup(build) {
		build.onEnd(async (result) => {
			if (deployTo === undefined || result.errors.length > 0) return;
			try {
				await mkdir(deployTo, { recursive: true });
				for (const file of ['main.js', 'manifest.json', 'styles.css']) {
					if (existsSync(file)) await copyFile(file, join(deployTo, file));
				}
				await writeFile(join(deployTo, '.hotreload'), '');
				console.log(`[deploy] ${deployTo}`);
			} catch (error) {
				// A vault that is not there must not break the build.
				console.log(`[deploy] skipped: ${error.message}`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [deployPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
